swagger: "2.0"
info:
  description: "Workflow engine RESTful interface."
  version: "1.0.0"
  title: "Workflow Engine"
  contact:
    email: "maxshugar@hotmail.co.uk"
basePath: "/v1"
tags:
- name: "Script"
  description: "Scripts to be executed on the target."
- name: "Sequence"
  description: "Script execution sequence."
schemes:
- "http"
paths:
  /script:
    get:
      tags:
      - "Script"
      summary: "Get all scripts."
      description: "Retrieve all scripts loaded on the target."
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
        "400":
          description: "Invalid status value"
    post:
      tags:
      - "Script"
      summary: "Load a script into memory and evaluate for syntax errors."
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "A script to be added to the engine."
        required: true
        schema:
          $ref: "#/definitions/Script"
      responses:
        "405":
          description: "Invalid input"
  /script/{scriptId}:
    get:
      tags:
      - "Script"
      summary: "Get a specific script."
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "scriptId"
        in: "path"
        description: "The id of the script."
        required: true
        type: "string"
        format: "guid"
      responses:
        "200":
          description: "Script found."
        "404":
          description: "Script not found."
    put:
      tags:
      - "Script"
      summary: "Update an existing script and evaluate for syntax errors."
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "scriptId"
        in: "path"
        description: "The id of the script to be updated."
        required: true
        type: "string"
        format: "guid"
      responses:
        "200":
          description: "Script found."
        "404":
          description: "Script not found."
        "405":
          description: "Script invalid."
    delete:
      tags:
      - "Script"
      summary: "Deletes a script"
      produces:
      - "application/json"
      parameters:
      - name: "scriptId"
        in: "path"
        required: true
        type: "string"
        description: "Script id to delete"
        format: "guid"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Pet not found"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"  
  /script/{scriptId}/execute:
    post:
      tags:
      - "Script"
      summary: "Executes a script."
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "scriptId"
        in: "path"
        description: "The id of the script to be executed."
        required: true
        type: "string"
        format: "guid"
      responses:
        "200":
          description: "Script executed."
        "404":
          description: "Script not found."
        "405":
          description: "Script invalid."
        
  /sequence:
    get:
      tags:
      - "Sequence"
      summary: "Get all sequences"
      description: "Retrieve all sequences on the target."
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
        "400":
          description: "Invalid status value"
    post:
      tags:
      - "Sequence"
      summary: "Load a sequence into memory, validate flow and check for syntax errors."
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "A sequence to be added to the engine."
        required: true
        schema:
          $ref: "#/definitions/Script"
      responses:
        "405":
          description: "Invalid input"
  /sequence/{sequenceId}:
    get:
      tags:
      - "Sequence"
      summary: "Get a specific sequence."
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "sequenceId"
        in: "path"
        description: "The id of the sequence."
        required: true
        type: "string"
        format: "guid"
      responses:
        "200":
          description: "Script found."
        "404":
          description: "Script not found."
    put:
      tags:
      - "Sequence"
      summary: "Update an existing sequence and evaluate for syntax errors."
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "sequenceId"
        in: "path"
        description: "The id of the script to be updated."
        required: true
        type: "string"
        format: "guid"
      responses:
        "200":
          description: "Script found."
        "404":
          description: "Script not found."
        "405":
          description: "Script invalid."
    delete:
      tags:
      - "Sequence"
      summary: "Deletes a sequence."
      produces:
      - "application/json"
      parameters:
      - name: "sequenceId"
        in: "path"
        required: true
        type: "string"
        description: "Sequence id to delete"
        format: "guid"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Pet not found"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"
  /sequence/{sequenceId}/execute:
    post:
      tags:
      - "Sequence"
      summary: "Executes a sequence."
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "sequenceId"
        in: "path"
        description: "The id of the sequence to be executed."
        required: true
        type: "string"
        format: "guid"
      responses:
        "200":
          description: "Sequence executed."
        "404":
          description: "Sequence not found."
        "405":
          description: "Sequence invalid."
          
securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
definitions:
  Script:
    type: "object"
    properties:
      code:
        type: "string"
      type: 
        type: "string"